// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feed/settlement_stream.proto

package feed

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OutcomeSettlement_SettlementType int32

const (
	OutcomeSettlement_unknown   OutcomeSettlement_SettlementType = 0
	OutcomeSettlement_UNSETTLED OutcomeSettlement_SettlementType = 1
	OutcomeSettlement_WIN       OutcomeSettlement_SettlementType = 2
	OutcomeSettlement_LOSE      OutcomeSettlement_SettlementType = 3
	OutcomeSettlement_RETURN    OutcomeSettlement_SettlementType = 4
)

var OutcomeSettlement_SettlementType_name = map[int32]string{
	0: "unknown",
	1: "UNSETTLED",
	2: "WIN",
	3: "LOSE",
	4: "RETURN",
}
var OutcomeSettlement_SettlementType_value = map[string]int32{
	"unknown":   0,
	"UNSETTLED": 1,
	"WIN":       2,
	"LOSE":      3,
	"RETURN":    4,
}

func (x OutcomeSettlement_SettlementType) String() string {
	return proto.EnumName(OutcomeSettlement_SettlementType_name, int32(x))
}
func (OutcomeSettlement_SettlementType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_settlement_stream_18bf3a864deafee3, []int{5, 0}
}

type StreamSettlementsRequest struct {
	ClientName            string               `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	LastConsumedTimestamp *timestamp.Timestamp `protobuf:"bytes,2,opt,name=last_consumed_timestamp,json=lastConsumedTimestamp,proto3" json:"last_consumed_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *StreamSettlementsRequest) Reset()         { *m = StreamSettlementsRequest{} }
func (m *StreamSettlementsRequest) String() string { return proto.CompactTextString(m) }
func (*StreamSettlementsRequest) ProtoMessage()    {}
func (*StreamSettlementsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_settlement_stream_18bf3a864deafee3, []int{0}
}
func (m *StreamSettlementsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamSettlementsRequest.Unmarshal(m, b)
}
func (m *StreamSettlementsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamSettlementsRequest.Marshal(b, m, deterministic)
}
func (dst *StreamSettlementsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamSettlementsRequest.Merge(dst, src)
}
func (m *StreamSettlementsRequest) XXX_Size() int {
	return xxx_messageInfo_StreamSettlementsRequest.Size(m)
}
func (m *StreamSettlementsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamSettlementsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamSettlementsRequest proto.InternalMessageInfo

func (m *StreamSettlementsRequest) GetClientName() string {
	if m != nil {
		return m.ClientName
	}
	return ""
}

func (m *StreamSettlementsRequest) GetLastConsumedTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.LastConsumedTimestamp
	}
	return nil
}

type StreamSettlementsResponse struct {
	// Types that are valid to be assigned to Data:
	//	*StreamSettlementsResponse_MultipleEventsSettlement
	//	*StreamSettlementsResponse_RecoveryComplete
	Data                 isStreamSettlementsResponse_Data `protobuf_oneof:"data"`
	DiffTimestamp        *timestamp.Timestamp             `protobuf:"bytes,3,opt,name=diff_timestamp,json=diffTimestamp,proto3" json:"diff_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *StreamSettlementsResponse) Reset()         { *m = StreamSettlementsResponse{} }
func (m *StreamSettlementsResponse) String() string { return proto.CompactTextString(m) }
func (*StreamSettlementsResponse) ProtoMessage()    {}
func (*StreamSettlementsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_settlement_stream_18bf3a864deafee3, []int{1}
}
func (m *StreamSettlementsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamSettlementsResponse.Unmarshal(m, b)
}
func (m *StreamSettlementsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamSettlementsResponse.Marshal(b, m, deterministic)
}
func (dst *StreamSettlementsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamSettlementsResponse.Merge(dst, src)
}
func (m *StreamSettlementsResponse) XXX_Size() int {
	return xxx_messageInfo_StreamSettlementsResponse.Size(m)
}
func (m *StreamSettlementsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamSettlementsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamSettlementsResponse proto.InternalMessageInfo

type isStreamSettlementsResponse_Data interface {
	isStreamSettlementsResponse_Data()
}

type StreamSettlementsResponse_MultipleEventsSettlement struct {
	MultipleEventsSettlement *MultipleEventsSettlement `protobuf:"bytes,1,opt,name=multiple_events_settlement,json=multipleEventsSettlement,proto3,oneof"`
}

type StreamSettlementsResponse_RecoveryComplete struct {
	RecoveryComplete *SettlementRecoveryComplete `protobuf:"bytes,2,opt,name=recovery_complete,json=recoveryComplete,proto3,oneof"`
}

func (*StreamSettlementsResponse_MultipleEventsSettlement) isStreamSettlementsResponse_Data() {}

func (*StreamSettlementsResponse_RecoveryComplete) isStreamSettlementsResponse_Data() {}

func (m *StreamSettlementsResponse) GetData() isStreamSettlementsResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *StreamSettlementsResponse) GetMultipleEventsSettlement() *MultipleEventsSettlement {
	if x, ok := m.GetData().(*StreamSettlementsResponse_MultipleEventsSettlement); ok {
		return x.MultipleEventsSettlement
	}
	return nil
}

func (m *StreamSettlementsResponse) GetRecoveryComplete() *SettlementRecoveryComplete {
	if x, ok := m.GetData().(*StreamSettlementsResponse_RecoveryComplete); ok {
		return x.RecoveryComplete
	}
	return nil
}

func (m *StreamSettlementsResponse) GetDiffTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.DiffTimestamp
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*StreamSettlementsResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _StreamSettlementsResponse_OneofMarshaler, _StreamSettlementsResponse_OneofUnmarshaler, _StreamSettlementsResponse_OneofSizer, []interface{}{
		(*StreamSettlementsResponse_MultipleEventsSettlement)(nil),
		(*StreamSettlementsResponse_RecoveryComplete)(nil),
	}
}

func _StreamSettlementsResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*StreamSettlementsResponse)
	// data
	switch x := m.Data.(type) {
	case *StreamSettlementsResponse_MultipleEventsSettlement:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MultipleEventsSettlement); err != nil {
			return err
		}
	case *StreamSettlementsResponse_RecoveryComplete:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RecoveryComplete); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("StreamSettlementsResponse.Data has unexpected type %T", x)
	}
	return nil
}

func _StreamSettlementsResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*StreamSettlementsResponse)
	switch tag {
	case 1: // data.multiple_events_settlement
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MultipleEventsSettlement)
		err := b.DecodeMessage(msg)
		m.Data = &StreamSettlementsResponse_MultipleEventsSettlement{msg}
		return true, err
	case 2: // data.recovery_complete
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SettlementRecoveryComplete)
		err := b.DecodeMessage(msg)
		m.Data = &StreamSettlementsResponse_RecoveryComplete{msg}
		return true, err
	default:
		return false, nil
	}
}

func _StreamSettlementsResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*StreamSettlementsResponse)
	// data
	switch x := m.Data.(type) {
	case *StreamSettlementsResponse_MultipleEventsSettlement:
		s := proto.Size(x.MultipleEventsSettlement)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamSettlementsResponse_RecoveryComplete:
		s := proto.Size(x.RecoveryComplete)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SettlementRecoveryComplete struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettlementRecoveryComplete) Reset()         { *m = SettlementRecoveryComplete{} }
func (m *SettlementRecoveryComplete) String() string { return proto.CompactTextString(m) }
func (*SettlementRecoveryComplete) ProtoMessage()    {}
func (*SettlementRecoveryComplete) Descriptor() ([]byte, []int) {
	return fileDescriptor_settlement_stream_18bf3a864deafee3, []int{2}
}
func (m *SettlementRecoveryComplete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettlementRecoveryComplete.Unmarshal(m, b)
}
func (m *SettlementRecoveryComplete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettlementRecoveryComplete.Marshal(b, m, deterministic)
}
func (dst *SettlementRecoveryComplete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettlementRecoveryComplete.Merge(dst, src)
}
func (m *SettlementRecoveryComplete) XXX_Size() int {
	return xxx_messageInfo_SettlementRecoveryComplete.Size(m)
}
func (m *SettlementRecoveryComplete) XXX_DiscardUnknown() {
	xxx_messageInfo_SettlementRecoveryComplete.DiscardUnknown(m)
}

var xxx_messageInfo_SettlementRecoveryComplete proto.InternalMessageInfo

type MultipleEventsSettlement struct {
	EventSettlement      []*EventSettlement `protobuf:"bytes,1,rep,name=event_settlement,json=eventSettlement,proto3" json:"event_settlement,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MultipleEventsSettlement) Reset()         { *m = MultipleEventsSettlement{} }
func (m *MultipleEventsSettlement) String() string { return proto.CompactTextString(m) }
func (*MultipleEventsSettlement) ProtoMessage()    {}
func (*MultipleEventsSettlement) Descriptor() ([]byte, []int) {
	return fileDescriptor_settlement_stream_18bf3a864deafee3, []int{3}
}
func (m *MultipleEventsSettlement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultipleEventsSettlement.Unmarshal(m, b)
}
func (m *MultipleEventsSettlement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultipleEventsSettlement.Marshal(b, m, deterministic)
}
func (dst *MultipleEventsSettlement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultipleEventsSettlement.Merge(dst, src)
}
func (m *MultipleEventsSettlement) XXX_Size() int {
	return xxx_messageInfo_MultipleEventsSettlement.Size(m)
}
func (m *MultipleEventsSettlement) XXX_DiscardUnknown() {
	xxx_messageInfo_MultipleEventsSettlement.DiscardUnknown(m)
}

var xxx_messageInfo_MultipleEventsSettlement proto.InternalMessageInfo

func (m *MultipleEventsSettlement) GetEventSettlement() []*EventSettlement {
	if m != nil {
		return m.EventSettlement
	}
	return nil
}

type EventSettlement struct {
	EventId              string                        `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Resulting            *EventPoints                  `protobuf:"bytes,2,opt,name=resulting,proto3" json:"resulting,omitempty"`
	Outcomes             map[string]*OutcomeSettlement `protobuf:"bytes,3,rep,name=outcomes,proto3" json:"outcomes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *EventSettlement) Reset()         { *m = EventSettlement{} }
func (m *EventSettlement) String() string { return proto.CompactTextString(m) }
func (*EventSettlement) ProtoMessage()    {}
func (*EventSettlement) Descriptor() ([]byte, []int) {
	return fileDescriptor_settlement_stream_18bf3a864deafee3, []int{4}
}
func (m *EventSettlement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventSettlement.Unmarshal(m, b)
}
func (m *EventSettlement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventSettlement.Marshal(b, m, deterministic)
}
func (dst *EventSettlement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSettlement.Merge(dst, src)
}
func (m *EventSettlement) XXX_Size() int {
	return xxx_messageInfo_EventSettlement.Size(m)
}
func (m *EventSettlement) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSettlement.DiscardUnknown(m)
}

var xxx_messageInfo_EventSettlement proto.InternalMessageInfo

func (m *EventSettlement) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *EventSettlement) GetResulting() *EventPoints {
	if m != nil {
		return m.Resulting
	}
	return nil
}

func (m *EventSettlement) GetOutcomes() map[string]*OutcomeSettlement {
	if m != nil {
		return m.Outcomes
	}
	return nil
}

type OutcomeSettlement struct {
	Settlement           OutcomeSettlement_SettlementType `protobuf:"varint,1,opt,name=settlement,proto3,enum=feed.OutcomeSettlement_SettlementType" json:"settlement,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *OutcomeSettlement) Reset()         { *m = OutcomeSettlement{} }
func (m *OutcomeSettlement) String() string { return proto.CompactTextString(m) }
func (*OutcomeSettlement) ProtoMessage()    {}
func (*OutcomeSettlement) Descriptor() ([]byte, []int) {
	return fileDescriptor_settlement_stream_18bf3a864deafee3, []int{5}
}
func (m *OutcomeSettlement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutcomeSettlement.Unmarshal(m, b)
}
func (m *OutcomeSettlement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutcomeSettlement.Marshal(b, m, deterministic)
}
func (dst *OutcomeSettlement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutcomeSettlement.Merge(dst, src)
}
func (m *OutcomeSettlement) XXX_Size() int {
	return xxx_messageInfo_OutcomeSettlement.Size(m)
}
func (m *OutcomeSettlement) XXX_DiscardUnknown() {
	xxx_messageInfo_OutcomeSettlement.DiscardUnknown(m)
}

var xxx_messageInfo_OutcomeSettlement proto.InternalMessageInfo

func (m *OutcomeSettlement) GetSettlement() OutcomeSettlement_SettlementType {
	if m != nil {
		return m.Settlement
	}
	return OutcomeSettlement_unknown
}

func init() {
	proto.RegisterType((*StreamSettlementsRequest)(nil), "feed.StreamSettlementsRequest")
	proto.RegisterType((*StreamSettlementsResponse)(nil), "feed.StreamSettlementsResponse")
	proto.RegisterType((*SettlementRecoveryComplete)(nil), "feed.SettlementRecoveryComplete")
	proto.RegisterType((*MultipleEventsSettlement)(nil), "feed.MultipleEventsSettlement")
	proto.RegisterType((*EventSettlement)(nil), "feed.EventSettlement")
	proto.RegisterMapType((map[string]*OutcomeSettlement)(nil), "feed.EventSettlement.OutcomesEntry")
	proto.RegisterType((*OutcomeSettlement)(nil), "feed.OutcomeSettlement")
	proto.RegisterEnum("feed.OutcomeSettlement_SettlementType", OutcomeSettlement_SettlementType_name, OutcomeSettlement_SettlementType_value)
}

func init() {
	proto.RegisterFile("feed/settlement_stream.proto", fileDescriptor_settlement_stream_18bf3a864deafee3)
}

var fileDescriptor_settlement_stream_18bf3a864deafee3 = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcb, 0x6e, 0xda, 0x50,
	0x10, 0xc5, 0x98, 0xf2, 0x18, 0x04, 0x31, 0x57, 0x8a, 0x70, 0xac, 0xa8, 0x41, 0xae, 0x54, 0xb1,
	0xa9, 0x91, 0xe8, 0xa6, 0xea, 0xa6, 0x8f, 0xd4, 0x55, 0xa2, 0xa6, 0x50, 0x5d, 0x1c, 0x75, 0x53,
	0xd5, 0x72, 0xf0, 0x80, 0xac, 0xd8, 0xbe, 0xae, 0xef, 0x35, 0x15, 0x5f, 0xd1, 0x65, 0x7f, 0xa1,
	0x1f, 0xd8, 0x0f, 0xa8, 0xfc, 0x00, 0x0c, 0x0d, 0xca, 0xce, 0x9e, 0x39, 0xe7, 0xcc, 0x39, 0x73,
	0x07, 0xce, 0x17, 0x88, 0xee, 0x88, 0xa3, 0x10, 0x3e, 0x06, 0x18, 0x0a, 0x9b, 0x8b, 0x18, 0x9d,
	0xc0, 0x88, 0x62, 0x26, 0x18, 0xa9, 0xa5, 0x5d, 0xed, 0x62, 0xc9, 0xd8, 0xd2, 0xc7, 0x51, 0x56,
	0xbb, 0x4b, 0x16, 0x23, 0xe1, 0x05, 0xc8, 0x85, 0x13, 0x44, 0x39, 0x4c, 0xeb, 0x67, 0x22, 0xb8,
	0x4a, 0xf9, 0x11, 0xf3, 0x42, 0xc1, 0xf3, 0x86, 0xfe, 0x4b, 0x02, 0x75, 0x96, 0x09, 0xce, 0xb6,
	0x13, 0x38, 0xc5, 0x1f, 0x09, 0x72, 0x41, 0x2e, 0xa0, 0x3d, 0xf7, 0xbd, 0x94, 0x13, 0x3a, 0x01,
	0xaa, 0xd2, 0x40, 0x1a, 0xb6, 0x28, 0xe4, 0xa5, 0x89, 0x13, 0x20, 0xa1, 0xd0, 0xf7, 0x1d, 0x2e,
	0xec, 0x39, 0x0b, 0x79, 0x12, 0xa0, 0x6b, 0x6f, 0xe7, 0xaa, 0xd5, 0x81, 0x34, 0x6c, 0x8f, 0x35,
	0x23, 0x77, 0x66, 0x6c, 0x9c, 0x19, 0xd6, 0x06, 0x41, 0x4f, 0x53, 0xea, 0x65, 0xc1, 0xdc, 0x96,
	0xf5, 0xdf, 0x55, 0x38, 0x7b, 0xc0, 0x11, 0x8f, 0x58, 0xc8, 0x91, 0x7c, 0x07, 0x2d, 0x48, 0x7c,
	0xe1, 0x45, 0x3e, 0xda, 0x59, 0x1c, 0x6e, 0xef, 0x56, 0x93, 0x39, 0x6c, 0x8f, 0x9f, 0x1a, 0x69,
	0x5a, 0xe3, 0x73, 0x81, 0x33, 0x33, 0xd8, 0x4e, 0xec, 0xaa, 0x42, 0xd5, 0xe0, 0x48, 0x8f, 0x4c,
	0xa1, 0x17, 0xe3, 0x9c, 0xad, 0x30, 0x5e, 0xdb, 0x73, 0x16, 0x44, 0x3e, 0x0a, 0x2c, 0xb2, 0x0c,
	0x72, 0xd9, 0x1d, 0x98, 0x16, 0xc0, 0xcb, 0x02, 0x77, 0x55, 0xa1, 0x4a, 0x7c, 0x50, 0x23, 0xef,
	0xa0, 0xeb, 0x7a, 0x8b, 0x45, 0x69, 0x33, 0xf2, 0xa3, 0x9b, 0xe9, 0xa4, 0x8c, 0xed, 0xef, 0xfb,
	0x3a, 0xd4, 0x5c, 0x47, 0x38, 0xfa, 0x39, 0x68, 0xc7, 0x87, 0xeb, 0xdf, 0x40, 0x3d, 0x96, 0x98,
	0xbc, 0x05, 0x25, 0x7f, 0xfb, 0xbd, 0x5d, 0xc9, 0xc3, 0xf6, 0xf8, 0x34, 0x0f, 0x95, 0x31, 0x4a,
	0xe2, 0x27, 0xb8, 0x5f, 0xd0, 0xff, 0x4a, 0x70, 0x72, 0x00, 0x22, 0x67, 0xd0, 0xcc, 0x55, 0x3d,
	0xb7, 0xb8, 0x8d, 0x46, 0xf6, 0x7f, 0xed, 0x92, 0x11, 0xb4, 0x62, 0xe4, 0xa9, 0x9d, 0x70, 0x59,
	0xac, 0xaf, 0x57, 0x9a, 0xf4, 0x25, 0x3b, 0x41, 0xba, 0xc3, 0x90, 0x37, 0xd0, 0x64, 0x89, 0x98,
	0xb3, 0x00, 0xb9, 0x2a, 0x67, 0xce, 0x9e, 0x3d, 0xe8, 0xcc, 0x98, 0x16, 0x28, 0x33, 0x14, 0xf1,
	0x9a, 0x6e, 0x49, 0x9a, 0x05, 0x9d, 0xbd, 0x16, 0x51, 0x40, 0xbe, 0xc7, 0x75, 0x61, 0x2c, 0xfd,
	0x24, 0x2f, 0xe0, 0xc9, 0xca, 0xf1, 0x93, 0xcd, 0x7b, 0xf6, 0xf3, 0x01, 0x05, 0xab, 0x14, 0x3e,
	0x47, 0xbd, 0xae, 0xbe, 0x92, 0xf4, 0x3f, 0x12, 0xf4, 0xfe, 0x03, 0x90, 0x8f, 0x00, 0x07, 0x47,
	0xd7, 0x1d, 0x3f, 0x3f, 0xa2, 0x56, 0xba, 0x17, 0x6b, 0x1d, 0x21, 0x2d, 0x31, 0xf5, 0x4f, 0xd0,
	0xdd, 0xef, 0x92, 0x36, 0x34, 0x92, 0xf0, 0x3e, 0x64, 0x3f, 0x43, 0xa5, 0x42, 0x3a, 0xd0, 0xba,
	0x9d, 0xcc, 0x4c, 0xcb, 0xba, 0x31, 0x3f, 0x28, 0x12, 0x69, 0x80, 0xfc, 0xf5, 0x7a, 0xa2, 0x54,
	0x49, 0x13, 0x6a, 0x37, 0xd3, 0x99, 0xa9, 0xc8, 0x04, 0xa0, 0x4e, 0x4d, 0xeb, 0x96, 0x4e, 0x94,
	0xda, 0x5d, 0x3d, 0x3b, 0xa4, 0x97, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x03, 0x47, 0x87,
	0x30, 0x04, 0x00, 0x00,
}
