// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feed/settlement_stream.proto

package feed

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OutcomeSettlement_SettlementType int32

const (
	OutcomeSettlement_unknown   OutcomeSettlement_SettlementType = 0
	OutcomeSettlement_UNSETTLED OutcomeSettlement_SettlementType = 1
	OutcomeSettlement_WIN       OutcomeSettlement_SettlementType = 2
	OutcomeSettlement_LOSE      OutcomeSettlement_SettlementType = 3
	OutcomeSettlement_RETURN    OutcomeSettlement_SettlementType = 4
)

var OutcomeSettlement_SettlementType_name = map[int32]string{
	0: "unknown",
	1: "UNSETTLED",
	2: "WIN",
	3: "LOSE",
	4: "RETURN",
}
var OutcomeSettlement_SettlementType_value = map[string]int32{
	"unknown":   0,
	"UNSETTLED": 1,
	"WIN":       2,
	"LOSE":      3,
	"RETURN":    4,
}

func (x OutcomeSettlement_SettlementType) String() string {
	return proto.EnumName(OutcomeSettlement_SettlementType_name, int32(x))
}
func (OutcomeSettlement_SettlementType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_settlement_stream_c014a156085ef231, []int{6, 0}
}

type StreamSettlementsRequest struct {
	ClientName            string               `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	LastConsumedTimestamp *timestamp.Timestamp `protobuf:"bytes,2,opt,name=last_consumed_timestamp,json=lastConsumedTimestamp,proto3" json:"last_consumed_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *StreamSettlementsRequest) Reset()         { *m = StreamSettlementsRequest{} }
func (m *StreamSettlementsRequest) String() string { return proto.CompactTextString(m) }
func (*StreamSettlementsRequest) ProtoMessage()    {}
func (*StreamSettlementsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_settlement_stream_c014a156085ef231, []int{0}
}
func (m *StreamSettlementsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamSettlementsRequest.Unmarshal(m, b)
}
func (m *StreamSettlementsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamSettlementsRequest.Marshal(b, m, deterministic)
}
func (dst *StreamSettlementsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamSettlementsRequest.Merge(dst, src)
}
func (m *StreamSettlementsRequest) XXX_Size() int {
	return xxx_messageInfo_StreamSettlementsRequest.Size(m)
}
func (m *StreamSettlementsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamSettlementsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamSettlementsRequest proto.InternalMessageInfo

func (m *StreamSettlementsRequest) GetClientName() string {
	if m != nil {
		return m.ClientName
	}
	return ""
}

func (m *StreamSettlementsRequest) GetLastConsumedTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.LastConsumedTimestamp
	}
	return nil
}

type StreamSettlementsResponse struct {
	// Types that are valid to be assigned to Data:
	//	*StreamSettlementsResponse_MultipleEventsSettlement
	//	*StreamSettlementsResponse_RecoveryComplete
	Data                 isStreamSettlementsResponse_Data `protobuf_oneof:"data"`
	DiffTimestamp        *timestamp.Timestamp             `protobuf:"bytes,3,opt,name=diff_timestamp,json=diffTimestamp,proto3" json:"diff_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *StreamSettlementsResponse) Reset()         { *m = StreamSettlementsResponse{} }
func (m *StreamSettlementsResponse) String() string { return proto.CompactTextString(m) }
func (*StreamSettlementsResponse) ProtoMessage()    {}
func (*StreamSettlementsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_settlement_stream_c014a156085ef231, []int{1}
}
func (m *StreamSettlementsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamSettlementsResponse.Unmarshal(m, b)
}
func (m *StreamSettlementsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamSettlementsResponse.Marshal(b, m, deterministic)
}
func (dst *StreamSettlementsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamSettlementsResponse.Merge(dst, src)
}
func (m *StreamSettlementsResponse) XXX_Size() int {
	return xxx_messageInfo_StreamSettlementsResponse.Size(m)
}
func (m *StreamSettlementsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamSettlementsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamSettlementsResponse proto.InternalMessageInfo

type isStreamSettlementsResponse_Data interface {
	isStreamSettlementsResponse_Data()
}

type StreamSettlementsResponse_MultipleEventsSettlement struct {
	MultipleEventsSettlement *MultipleEventsSettlement `protobuf:"bytes,1,opt,name=multiple_events_settlement,json=multipleEventsSettlement,proto3,oneof"`
}

type StreamSettlementsResponse_RecoveryComplete struct {
	RecoveryComplete *SettlementRecoveryComplete `protobuf:"bytes,2,opt,name=recovery_complete,json=recoveryComplete,proto3,oneof"`
}

func (*StreamSettlementsResponse_MultipleEventsSettlement) isStreamSettlementsResponse_Data() {}

func (*StreamSettlementsResponse_RecoveryComplete) isStreamSettlementsResponse_Data() {}

func (m *StreamSettlementsResponse) GetData() isStreamSettlementsResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *StreamSettlementsResponse) GetMultipleEventsSettlement() *MultipleEventsSettlement {
	if x, ok := m.GetData().(*StreamSettlementsResponse_MultipleEventsSettlement); ok {
		return x.MultipleEventsSettlement
	}
	return nil
}

func (m *StreamSettlementsResponse) GetRecoveryComplete() *SettlementRecoveryComplete {
	if x, ok := m.GetData().(*StreamSettlementsResponse_RecoveryComplete); ok {
		return x.RecoveryComplete
	}
	return nil
}

func (m *StreamSettlementsResponse) GetDiffTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.DiffTimestamp
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*StreamSettlementsResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _StreamSettlementsResponse_OneofMarshaler, _StreamSettlementsResponse_OneofUnmarshaler, _StreamSettlementsResponse_OneofSizer, []interface{}{
		(*StreamSettlementsResponse_MultipleEventsSettlement)(nil),
		(*StreamSettlementsResponse_RecoveryComplete)(nil),
	}
}

func _StreamSettlementsResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*StreamSettlementsResponse)
	// data
	switch x := m.Data.(type) {
	case *StreamSettlementsResponse_MultipleEventsSettlement:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MultipleEventsSettlement); err != nil {
			return err
		}
	case *StreamSettlementsResponse_RecoveryComplete:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RecoveryComplete); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("StreamSettlementsResponse.Data has unexpected type %T", x)
	}
	return nil
}

func _StreamSettlementsResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*StreamSettlementsResponse)
	switch tag {
	case 1: // data.multiple_events_settlement
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MultipleEventsSettlement)
		err := b.DecodeMessage(msg)
		m.Data = &StreamSettlementsResponse_MultipleEventsSettlement{msg}
		return true, err
	case 2: // data.recovery_complete
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SettlementRecoveryComplete)
		err := b.DecodeMessage(msg)
		m.Data = &StreamSettlementsResponse_RecoveryComplete{msg}
		return true, err
	default:
		return false, nil
	}
}

func _StreamSettlementsResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*StreamSettlementsResponse)
	// data
	switch x := m.Data.(type) {
	case *StreamSettlementsResponse_MultipleEventsSettlement:
		s := proto.Size(x.MultipleEventsSettlement)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamSettlementsResponse_RecoveryComplete:
		s := proto.Size(x.RecoveryComplete)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SettlementRecoveryComplete struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettlementRecoveryComplete) Reset()         { *m = SettlementRecoveryComplete{} }
func (m *SettlementRecoveryComplete) String() string { return proto.CompactTextString(m) }
func (*SettlementRecoveryComplete) ProtoMessage()    {}
func (*SettlementRecoveryComplete) Descriptor() ([]byte, []int) {
	return fileDescriptor_settlement_stream_c014a156085ef231, []int{2}
}
func (m *SettlementRecoveryComplete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettlementRecoveryComplete.Unmarshal(m, b)
}
func (m *SettlementRecoveryComplete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettlementRecoveryComplete.Marshal(b, m, deterministic)
}
func (dst *SettlementRecoveryComplete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettlementRecoveryComplete.Merge(dst, src)
}
func (m *SettlementRecoveryComplete) XXX_Size() int {
	return xxx_messageInfo_SettlementRecoveryComplete.Size(m)
}
func (m *SettlementRecoveryComplete) XXX_DiscardUnknown() {
	xxx_messageInfo_SettlementRecoveryComplete.DiscardUnknown(m)
}

var xxx_messageInfo_SettlementRecoveryComplete proto.InternalMessageInfo

type MultipleEventsSettlement struct {
	EventSettlement      []*EventSettlement `protobuf:"bytes,1,rep,name=event_settlement,json=eventSettlement,proto3" json:"event_settlement,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MultipleEventsSettlement) Reset()         { *m = MultipleEventsSettlement{} }
func (m *MultipleEventsSettlement) String() string { return proto.CompactTextString(m) }
func (*MultipleEventsSettlement) ProtoMessage()    {}
func (*MultipleEventsSettlement) Descriptor() ([]byte, []int) {
	return fileDescriptor_settlement_stream_c014a156085ef231, []int{3}
}
func (m *MultipleEventsSettlement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultipleEventsSettlement.Unmarshal(m, b)
}
func (m *MultipleEventsSettlement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultipleEventsSettlement.Marshal(b, m, deterministic)
}
func (dst *MultipleEventsSettlement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultipleEventsSettlement.Merge(dst, src)
}
func (m *MultipleEventsSettlement) XXX_Size() int {
	return xxx_messageInfo_MultipleEventsSettlement.Size(m)
}
func (m *MultipleEventsSettlement) XXX_DiscardUnknown() {
	xxx_messageInfo_MultipleEventsSettlement.DiscardUnknown(m)
}

var xxx_messageInfo_MultipleEventsSettlement proto.InternalMessageInfo

func (m *MultipleEventsSettlement) GetEventSettlement() []*EventSettlement {
	if m != nil {
		return m.EventSettlement
	}
	return nil
}

type EventSettlement struct {
	EventId              string                        `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Resulting            *FeedResulting                `protobuf:"bytes,2,opt,name=resulting,proto3" json:"resulting,omitempty"`
	Outcomes             map[string]*OutcomeSettlement `protobuf:"bytes,3,rep,name=outcomes,proto3" json:"outcomes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *EventSettlement) Reset()         { *m = EventSettlement{} }
func (m *EventSettlement) String() string { return proto.CompactTextString(m) }
func (*EventSettlement) ProtoMessage()    {}
func (*EventSettlement) Descriptor() ([]byte, []int) {
	return fileDescriptor_settlement_stream_c014a156085ef231, []int{4}
}
func (m *EventSettlement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventSettlement.Unmarshal(m, b)
}
func (m *EventSettlement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventSettlement.Marshal(b, m, deterministic)
}
func (dst *EventSettlement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSettlement.Merge(dst, src)
}
func (m *EventSettlement) XXX_Size() int {
	return xxx_messageInfo_EventSettlement.Size(m)
}
func (m *EventSettlement) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSettlement.DiscardUnknown(m)
}

var xxx_messageInfo_EventSettlement proto.InternalMessageInfo

func (m *EventSettlement) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *EventSettlement) GetResulting() *FeedResulting {
	if m != nil {
		return m.Resulting
	}
	return nil
}

func (m *EventSettlement) GetOutcomes() map[string]*OutcomeSettlement {
	if m != nil {
		return m.Outcomes
	}
	return nil
}

type FeedResulting struct {
	ResultGroups         []*FeedResulting_ResultGroup `protobuf:"bytes,1,rep,name=result_groups,json=resultGroups,proto3" json:"result_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *FeedResulting) Reset()         { *m = FeedResulting{} }
func (m *FeedResulting) String() string { return proto.CompactTextString(m) }
func (*FeedResulting) ProtoMessage()    {}
func (*FeedResulting) Descriptor() ([]byte, []int) {
	return fileDescriptor_settlement_stream_c014a156085ef231, []int{5}
}
func (m *FeedResulting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedResulting.Unmarshal(m, b)
}
func (m *FeedResulting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedResulting.Marshal(b, m, deterministic)
}
func (dst *FeedResulting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedResulting.Merge(dst, src)
}
func (m *FeedResulting) XXX_Size() int {
	return xxx_messageInfo_FeedResulting.Size(m)
}
func (m *FeedResulting) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedResulting.DiscardUnknown(m)
}

var xxx_messageInfo_FeedResulting proto.InternalMessageInfo

func (m *FeedResulting) GetResultGroups() []*FeedResulting_ResultGroup {
	if m != nil {
		return m.ResultGroups
	}
	return nil
}

type FeedResulting_ResultGroup struct {
	ResultGroupId        int32                                        `protobuf:"varint,1,opt,name=result_group_id,json=resultGroupId,proto3" json:"result_group_id,omitempty"`
	Params               *FeedResulting_ResultGroup_ResultGroupParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	Results              []*FeedResulting_ResultGroup_Result          `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *FeedResulting_ResultGroup) Reset()         { *m = FeedResulting_ResultGroup{} }
func (m *FeedResulting_ResultGroup) String() string { return proto.CompactTextString(m) }
func (*FeedResulting_ResultGroup) ProtoMessage()    {}
func (*FeedResulting_ResultGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_settlement_stream_c014a156085ef231, []int{5, 0}
}
func (m *FeedResulting_ResultGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedResulting_ResultGroup.Unmarshal(m, b)
}
func (m *FeedResulting_ResultGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedResulting_ResultGroup.Marshal(b, m, deterministic)
}
func (dst *FeedResulting_ResultGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedResulting_ResultGroup.Merge(dst, src)
}
func (m *FeedResulting_ResultGroup) XXX_Size() int {
	return xxx_messageInfo_FeedResulting_ResultGroup.Size(m)
}
func (m *FeedResulting_ResultGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedResulting_ResultGroup.DiscardUnknown(m)
}

var xxx_messageInfo_FeedResulting_ResultGroup proto.InternalMessageInfo

func (m *FeedResulting_ResultGroup) GetResultGroupId() int32 {
	if m != nil {
		return m.ResultGroupId
	}
	return 0
}

func (m *FeedResulting_ResultGroup) GetParams() *FeedResulting_ResultGroup_ResultGroupParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *FeedResulting_ResultGroup) GetResults() []*FeedResulting_ResultGroup_Result {
	if m != nil {
		return m.Results
	}
	return nil
}

type FeedResulting_ResultGroup_ResultGroupParams struct {
	Period               int32    `protobuf:"varint,1,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedResulting_ResultGroup_ResultGroupParams) Reset() {
	*m = FeedResulting_ResultGroup_ResultGroupParams{}
}
func (m *FeedResulting_ResultGroup_ResultGroupParams) String() string {
	return proto.CompactTextString(m)
}
func (*FeedResulting_ResultGroup_ResultGroupParams) ProtoMessage() {}
func (*FeedResulting_ResultGroup_ResultGroupParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_settlement_stream_c014a156085ef231, []int{5, 0, 0}
}
func (m *FeedResulting_ResultGroup_ResultGroupParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedResulting_ResultGroup_ResultGroupParams.Unmarshal(m, b)
}
func (m *FeedResulting_ResultGroup_ResultGroupParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedResulting_ResultGroup_ResultGroupParams.Marshal(b, m, deterministic)
}
func (dst *FeedResulting_ResultGroup_ResultGroupParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedResulting_ResultGroup_ResultGroupParams.Merge(dst, src)
}
func (m *FeedResulting_ResultGroup_ResultGroupParams) XXX_Size() int {
	return xxx_messageInfo_FeedResulting_ResultGroup_ResultGroupParams.Size(m)
}
func (m *FeedResulting_ResultGroup_ResultGroupParams) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedResulting_ResultGroup_ResultGroupParams.DiscardUnknown(m)
}

var xxx_messageInfo_FeedResulting_ResultGroup_ResultGroupParams proto.InternalMessageInfo

func (m *FeedResulting_ResultGroup_ResultGroupParams) GetPeriod() int32 {
	if m != nil {
		return m.Period
	}
	return 0
}

type FeedResulting_ResultGroup_Result struct {
	Params               *FeedResulting_ResultGroup_Result_ResultParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Value                int32                                          `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *FeedResulting_ResultGroup_Result) Reset()         { *m = FeedResulting_ResultGroup_Result{} }
func (m *FeedResulting_ResultGroup_Result) String() string { return proto.CompactTextString(m) }
func (*FeedResulting_ResultGroup_Result) ProtoMessage()    {}
func (*FeedResulting_ResultGroup_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_settlement_stream_c014a156085ef231, []int{5, 0, 1}
}
func (m *FeedResulting_ResultGroup_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedResulting_ResultGroup_Result.Unmarshal(m, b)
}
func (m *FeedResulting_ResultGroup_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedResulting_ResultGroup_Result.Marshal(b, m, deterministic)
}
func (dst *FeedResulting_ResultGroup_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedResulting_ResultGroup_Result.Merge(dst, src)
}
func (m *FeedResulting_ResultGroup_Result) XXX_Size() int {
	return xxx_messageInfo_FeedResulting_ResultGroup_Result.Size(m)
}
func (m *FeedResulting_ResultGroup_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedResulting_ResultGroup_Result.DiscardUnknown(m)
}

var xxx_messageInfo_FeedResulting_ResultGroup_Result proto.InternalMessageInfo

func (m *FeedResulting_ResultGroup_Result) GetParams() *FeedResulting_ResultGroup_Result_ResultParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *FeedResulting_ResultGroup_Result) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type FeedResulting_ResultGroup_Result_ResultParams struct {
	Team                 int32    `protobuf:"varint,1,opt,name=team,proto3" json:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedResulting_ResultGroup_Result_ResultParams) Reset() {
	*m = FeedResulting_ResultGroup_Result_ResultParams{}
}
func (m *FeedResulting_ResultGroup_Result_ResultParams) String() string {
	return proto.CompactTextString(m)
}
func (*FeedResulting_ResultGroup_Result_ResultParams) ProtoMessage() {}
func (*FeedResulting_ResultGroup_Result_ResultParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_settlement_stream_c014a156085ef231, []int{5, 0, 1, 0}
}
func (m *FeedResulting_ResultGroup_Result_ResultParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedResulting_ResultGroup_Result_ResultParams.Unmarshal(m, b)
}
func (m *FeedResulting_ResultGroup_Result_ResultParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedResulting_ResultGroup_Result_ResultParams.Marshal(b, m, deterministic)
}
func (dst *FeedResulting_ResultGroup_Result_ResultParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedResulting_ResultGroup_Result_ResultParams.Merge(dst, src)
}
func (m *FeedResulting_ResultGroup_Result_ResultParams) XXX_Size() int {
	return xxx_messageInfo_FeedResulting_ResultGroup_Result_ResultParams.Size(m)
}
func (m *FeedResulting_ResultGroup_Result_ResultParams) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedResulting_ResultGroup_Result_ResultParams.DiscardUnknown(m)
}

var xxx_messageInfo_FeedResulting_ResultGroup_Result_ResultParams proto.InternalMessageInfo

func (m *FeedResulting_ResultGroup_Result_ResultParams) GetTeam() int32 {
	if m != nil {
		return m.Team
	}
	return 0
}

type OutcomeSettlement struct {
	Settlement           OutcomeSettlement_SettlementType `protobuf:"varint,1,opt,name=settlement,proto3,enum=feed.OutcomeSettlement_SettlementType" json:"settlement,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *OutcomeSettlement) Reset()         { *m = OutcomeSettlement{} }
func (m *OutcomeSettlement) String() string { return proto.CompactTextString(m) }
func (*OutcomeSettlement) ProtoMessage()    {}
func (*OutcomeSettlement) Descriptor() ([]byte, []int) {
	return fileDescriptor_settlement_stream_c014a156085ef231, []int{6}
}
func (m *OutcomeSettlement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutcomeSettlement.Unmarshal(m, b)
}
func (m *OutcomeSettlement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutcomeSettlement.Marshal(b, m, deterministic)
}
func (dst *OutcomeSettlement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutcomeSettlement.Merge(dst, src)
}
func (m *OutcomeSettlement) XXX_Size() int {
	return xxx_messageInfo_OutcomeSettlement.Size(m)
}
func (m *OutcomeSettlement) XXX_DiscardUnknown() {
	xxx_messageInfo_OutcomeSettlement.DiscardUnknown(m)
}

var xxx_messageInfo_OutcomeSettlement proto.InternalMessageInfo

func (m *OutcomeSettlement) GetSettlement() OutcomeSettlement_SettlementType {
	if m != nil {
		return m.Settlement
	}
	return OutcomeSettlement_unknown
}

func init() {
	proto.RegisterType((*StreamSettlementsRequest)(nil), "feed.StreamSettlementsRequest")
	proto.RegisterType((*StreamSettlementsResponse)(nil), "feed.StreamSettlementsResponse")
	proto.RegisterType((*SettlementRecoveryComplete)(nil), "feed.SettlementRecoveryComplete")
	proto.RegisterType((*MultipleEventsSettlement)(nil), "feed.MultipleEventsSettlement")
	proto.RegisterType((*EventSettlement)(nil), "feed.EventSettlement")
	proto.RegisterMapType((map[string]*OutcomeSettlement)(nil), "feed.EventSettlement.OutcomesEntry")
	proto.RegisterType((*FeedResulting)(nil), "feed.FeedResulting")
	proto.RegisterType((*FeedResulting_ResultGroup)(nil), "feed.FeedResulting.ResultGroup")
	proto.RegisterType((*FeedResulting_ResultGroup_ResultGroupParams)(nil), "feed.FeedResulting.ResultGroup.ResultGroupParams")
	proto.RegisterType((*FeedResulting_ResultGroup_Result)(nil), "feed.FeedResulting.ResultGroup.Result")
	proto.RegisterType((*FeedResulting_ResultGroup_Result_ResultParams)(nil), "feed.FeedResulting.ResultGroup.Result.ResultParams")
	proto.RegisterType((*OutcomeSettlement)(nil), "feed.OutcomeSettlement")
	proto.RegisterEnum("feed.OutcomeSettlement_SettlementType", OutcomeSettlement_SettlementType_name, OutcomeSettlement_SettlementType_value)
}

func init() {
	proto.RegisterFile("feed/settlement_stream.proto", fileDescriptor_settlement_stream_c014a156085ef231)
}

var fileDescriptor_settlement_stream_c014a156085ef231 = []byte{
	// 669 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xc1, 0x4e, 0xdb, 0x4a,
	0x14, 0xc5, 0x71, 0x48, 0xe0, 0x86, 0x80, 0x99, 0xf7, 0x78, 0x04, 0x0b, 0x3d, 0x90, 0x2b, 0x21,
	0xa4, 0xaa, 0x46, 0xc0, 0xa6, 0xea, 0xa6, 0xb4, 0x10, 0x4a, 0x04, 0x0d, 0xd5, 0x24, 0xa8, 0x9b,
	0xaa, 0x96, 0x89, 0x6f, 0xa2, 0x08, 0xdb, 0xe3, 0x7a, 0xc6, 0x54, 0x59, 0xf6, 0x0b, 0x58, 0xf6,
	0x17, 0xfa, 0x4b, 0xfd, 0x91, 0xae, 0x2b, 0x7b, 0xc6, 0x89, 0x13, 0x40, 0xb0, 0xca, 0xcc, 0xdc,
	0x73, 0xce, 0x3d, 0xf7, 0x4c, 0x3c, 0xb0, 0xd9, 0x47, 0xf4, 0xf6, 0x38, 0x0a, 0xe1, 0x63, 0x80,
	0xa1, 0x70, 0xb8, 0x88, 0xd1, 0x0d, 0xec, 0x28, 0x66, 0x82, 0x91, 0x72, 0x5a, 0x35, 0xb7, 0x06,
	0x8c, 0x0d, 0x7c, 0xdc, 0xcb, 0xce, 0xae, 0x93, 0xfe, 0x9e, 0x18, 0x06, 0xc8, 0x85, 0x1b, 0x44,
	0x12, 0x66, 0xdd, 0x69, 0xd0, 0xe8, 0x64, 0xbc, 0xce, 0x58, 0x88, 0x53, 0xfc, 0x96, 0x20, 0x17,
	0x64, 0x0b, 0x6a, 0x3d, 0x7f, 0x98, 0x4a, 0x87, 0x6e, 0x80, 0x0d, 0x6d, 0x5b, 0xdb, 0x5d, 0xa4,
	0x20, 0x8f, 0xda, 0x6e, 0x80, 0x84, 0xc2, 0xba, 0xef, 0x72, 0xe1, 0xf4, 0x58, 0xc8, 0x93, 0x00,
	0x3d, 0x67, 0x2c, 0xdf, 0x28, 0x6d, 0x6b, 0xbb, 0xb5, 0x03, 0xd3, 0x96, 0x06, 0xec, 0xdc, 0x80,
	0xdd, 0xcd, 0x11, 0x74, 0x2d, 0xa5, 0x1e, 0x2b, 0xe6, 0xf8, 0xd8, 0xfa, 0x59, 0x82, 0x8d, 0x07,
	0x1c, 0xf1, 0x88, 0x85, 0x1c, 0xc9, 0x57, 0x30, 0x83, 0xc4, 0x17, 0xc3, 0xc8, 0x47, 0x07, 0x6f,
	0xd3, 0x92, 0x33, 0x49, 0x20, 0x73, 0x58, 0x3b, 0xf8, 0xdf, 0x4e, 0x67, 0xb7, 0x3f, 0x2a, 0x5c,
	0x33, 0x83, 0x4d, 0xc4, 0xce, 0xe6, 0x68, 0x23, 0x78, 0xa4, 0x46, 0x2e, 0x61, 0x35, 0xc6, 0x1e,
	0xbb, 0xc5, 0x78, 0xe4, 0xf4, 0x58, 0x10, 0xf9, 0x28, 0x50, 0xcd, 0xb2, 0x2d, 0x65, 0x27, 0x60,
	0xaa, 0x80, 0xc7, 0x0a, 0x77, 0x36, 0x47, 0x8d, 0x78, 0xe6, 0x8c, 0xbc, 0x83, 0x65, 0x6f, 0xd8,
	0xef, 0x17, 0x92, 0xd1, 0x9f, 0x4c, 0xa6, 0x9e, 0x32, 0xc6, 0xdb, 0xf7, 0x15, 0x28, 0x7b, 0xae,
	0x70, 0xad, 0x4d, 0x30, 0x1f, 0x6f, 0x6e, 0x7d, 0x81, 0xc6, 0x63, 0x13, 0x93, 0x23, 0x30, 0xb2,
	0xb0, 0xa6, 0xb3, 0xd2, 0x77, 0x6b, 0x07, 0x6b, 0x72, 0xa8, 0x8c, 0x51, 0x10, 0x5f, 0xc1, 0xe9,
	0x03, 0xeb, 0x8f, 0x06, 0x2b, 0x33, 0x20, 0xb2, 0x01, 0x0b, 0x52, 0x75, 0xe8, 0xa9, 0xff, 0x46,
	0x35, 0xdb, 0xb7, 0x3c, 0xb2, 0x0f, 0x8b, 0x31, 0xf2, 0xd4, 0x4e, 0x38, 0x50, 0xf1, 0xfd, 0x23,
	0x3b, 0x9d, 0x22, 0x7a, 0x34, 0x2f, 0xd1, 0x09, 0x8a, 0xbc, 0x85, 0x05, 0x96, 0x88, 0x1e, 0x0b,
	0x90, 0x37, 0xf4, 0xcc, 0xdb, 0x8b, 0x07, 0xbd, 0xd9, 0x97, 0x0a, 0xd5, 0x0c, 0x45, 0x3c, 0xa2,
	0x63, 0x92, 0xd9, 0x85, 0xfa, 0x54, 0x89, 0x18, 0xa0, 0xdf, 0xe0, 0x48, 0x59, 0x4b, 0x97, 0xe4,
	0x15, 0xcc, 0xdf, 0xba, 0x7e, 0x92, 0xdf, 0xe8, 0xba, 0x6c, 0xa0, 0x58, 0x85, 0xf1, 0x25, 0xea,
	0x4d, 0xe9, 0xb5, 0x66, 0xfd, 0xd6, 0xa1, 0x3e, 0xe5, 0x99, 0x9c, 0x40, 0x5d, 0xba, 0x76, 0x06,
	0x31, 0x4b, 0x22, 0xae, 0x92, 0xdc, 0x7a, 0x60, 0x3e, 0x5b, 0xae, 0x3e, 0xa4, 0x38, 0xba, 0x14,
	0x4f, 0x36, 0xdc, 0xfc, 0xa1, 0x43, 0xad, 0x50, 0x25, 0x3b, 0xb0, 0x52, 0x54, 0xcd, 0x33, 0x9d,
	0xa7, 0xf5, 0x02, 0xad, 0xe5, 0x91, 0x16, 0x54, 0x22, 0x37, 0x76, 0x03, 0xae, 0x66, 0xd8, 0x7f,
	0xa2, 0x6d, 0x71, 0xfd, 0x29, 0x23, 0x52, 0x25, 0x40, 0x8e, 0xa0, 0x2a, 0xb5, 0xf3, 0xc0, 0x77,
	0x9e, 0xa7, 0x45, 0x73, 0x9a, 0xf9, 0x12, 0x56, 0xef, 0xc9, 0x93, 0xff, 0xa0, 0x12, 0x61, 0x3c,
	0x64, 0xf9, 0x00, 0x6a, 0x67, 0xde, 0x69, 0x50, 0x91, 0x68, 0x72, 0x3e, 0x1e, 0x42, 0x7e, 0xb1,
	0x87, 0xcf, 0x6b, 0xac, 0x7e, 0x66, 0xc6, 0xf8, 0xb7, 0x78, 0xa9, 0xf3, 0xea, 0xee, 0x4c, 0x0b,
	0x96, 0x8a, 0x68, 0x42, 0xa0, 0x2c, 0xd0, 0x0d, 0x94, 0xa7, 0x6c, 0x6d, 0xfd, 0xd2, 0x60, 0xf5,
	0xde, 0xe5, 0x93, 0x53, 0x80, 0x99, 0x27, 0x65, 0x39, 0x4f, 0xe6, 0x1e, 0xb8, 0xf0, 0x1a, 0x74,
	0x47, 0x11, 0xd2, 0x02, 0xd3, 0x3a, 0x87, 0xe5, 0xe9, 0x2a, 0xa9, 0x41, 0x35, 0x09, 0x6f, 0x42,
	0xf6, 0x3d, 0x34, 0xe6, 0x48, 0x1d, 0x16, 0xaf, 0xda, 0x9d, 0x66, 0xb7, 0x7b, 0xd1, 0x3c, 0x31,
	0x34, 0x52, 0x05, 0xfd, 0x73, 0xab, 0x6d, 0x94, 0xc8, 0x02, 0x94, 0x2f, 0x2e, 0x3b, 0x4d, 0x43,
	0x27, 0x00, 0x15, 0xda, 0xec, 0x5e, 0xd1, 0xb6, 0x51, 0xbe, 0xae, 0x64, 0xcf, 0xc4, 0xe1, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x2c, 0xc5, 0xc0, 0xfc, 0xf5, 0x05, 0x00, 0x00,
}
