// Code generated by protoc-gen-go. DO NOT EDIT.
// source: xfeed_proto/sport_descriptions.proto

package xfeed_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SportDescriptionsRequest struct {
	Lang                 string   `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SportDescriptionsRequest) Reset()         { *m = SportDescriptionsRequest{} }
func (m *SportDescriptionsRequest) String() string { return proto.CompactTextString(m) }
func (*SportDescriptionsRequest) ProtoMessage()    {}
func (*SportDescriptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_sport_descriptions_3f03905b69aaba44, []int{0}
}
func (m *SportDescriptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SportDescriptionsRequest.Unmarshal(m, b)
}
func (m *SportDescriptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SportDescriptionsRequest.Marshal(b, m, deterministic)
}
func (dst *SportDescriptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SportDescriptionsRequest.Merge(dst, src)
}
func (m *SportDescriptionsRequest) XXX_Size() int {
	return xxx_messageInfo_SportDescriptionsRequest.Size(m)
}
func (m *SportDescriptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SportDescriptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SportDescriptionsRequest proto.InternalMessageInfo

func (m *SportDescriptionsRequest) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

type SportDescriptionsResponse struct {
	SportDescriptions    []*SportDescription `protobuf:"bytes,1,rep,name=sport_descriptions,json=sportDescriptions,proto3" json:"sport_descriptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SportDescriptionsResponse) Reset()         { *m = SportDescriptionsResponse{} }
func (m *SportDescriptionsResponse) String() string { return proto.CompactTextString(m) }
func (*SportDescriptionsResponse) ProtoMessage()    {}
func (*SportDescriptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_sport_descriptions_3f03905b69aaba44, []int{1}
}
func (m *SportDescriptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SportDescriptionsResponse.Unmarshal(m, b)
}
func (m *SportDescriptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SportDescriptionsResponse.Marshal(b, m, deterministic)
}
func (dst *SportDescriptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SportDescriptionsResponse.Merge(dst, src)
}
func (m *SportDescriptionsResponse) XXX_Size() int {
	return xxx_messageInfo_SportDescriptionsResponse.Size(m)
}
func (m *SportDescriptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SportDescriptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SportDescriptionsResponse proto.InternalMessageInfo

func (m *SportDescriptionsResponse) GetSportDescriptions() []*SportDescription {
	if m != nil {
		return m.SportDescriptions
	}
	return nil
}

type SportDescription struct {
	SportId              int32         `protobuf:"varint,1,opt,name=sport_id,json=sportId,proto3" json:"sport_id,omitempty"`
	SportName            string        `protobuf:"bytes,2,opt,name=sport_name,json=sportName,proto3" json:"sport_name,omitempty"`
	Periods              []*Period     `protobuf:"bytes,3,rep,name=periods,proto3" json:"periods,omitempty"`
	MarketTypes          []*MarketType `protobuf:"bytes,4,rep,name=market_types,json=marketTypes,proto3" json:"market_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SportDescription) Reset()         { *m = SportDescription{} }
func (m *SportDescription) String() string { return proto.CompactTextString(m) }
func (*SportDescription) ProtoMessage()    {}
func (*SportDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_sport_descriptions_3f03905b69aaba44, []int{2}
}
func (m *SportDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SportDescription.Unmarshal(m, b)
}
func (m *SportDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SportDescription.Marshal(b, m, deterministic)
}
func (dst *SportDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SportDescription.Merge(dst, src)
}
func (m *SportDescription) XXX_Size() int {
	return xxx_messageInfo_SportDescription.Size(m)
}
func (m *SportDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_SportDescription.DiscardUnknown(m)
}

var xxx_messageInfo_SportDescription proto.InternalMessageInfo

func (m *SportDescription) GetSportId() int32 {
	if m != nil {
		return m.SportId
	}
	return 0
}

func (m *SportDescription) GetSportName() string {
	if m != nil {
		return m.SportName
	}
	return ""
}

func (m *SportDescription) GetPeriods() []*Period {
	if m != nil {
		return m.Periods
	}
	return nil
}

func (m *SportDescription) GetMarketTypes() []*MarketType {
	if m != nil {
		return m.MarketTypes
	}
	return nil
}

type Period struct {
	PeriodId             int32    `protobuf:"varint,1,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	PeriodName           string   `protobuf:"bytes,2,opt,name=period_name,json=periodName,proto3" json:"period_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Period) Reset()         { *m = Period{} }
func (m *Period) String() string { return proto.CompactTextString(m) }
func (*Period) ProtoMessage()    {}
func (*Period) Descriptor() ([]byte, []int) {
	return fileDescriptor_sport_descriptions_3f03905b69aaba44, []int{3}
}
func (m *Period) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Period.Unmarshal(m, b)
}
func (m *Period) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Period.Marshal(b, m, deterministic)
}
func (dst *Period) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Period.Merge(dst, src)
}
func (m *Period) XXX_Size() int {
	return xxx_messageInfo_Period.Size(m)
}
func (m *Period) XXX_DiscardUnknown() {
	xxx_messageInfo_Period.DiscardUnknown(m)
}

var xxx_messageInfo_Period proto.InternalMessageInfo

func (m *Period) GetPeriodId() int32 {
	if m != nil {
		return m.PeriodId
	}
	return 0
}

func (m *Period) GetPeriodName() string {
	if m != nil {
		return m.PeriodName
	}
	return ""
}

type MarketType struct {
	MarketTypeId int32 `protobuf:"varint,1,opt,name=market_type_id,json=marketTypeId,proto3" json:"market_type_id,omitempty"`
	// event.participants = ["Dinamo", "Shakhtar"]
	// market_params.team = 1
	// Ex.: "{%participant} Total" -> "Dinamo Total"
	MarketNameTemplate   string         `protobuf:"bytes,2,opt,name=market_name_template,json=marketNameTemplate,proto3" json:"market_name_template,omitempty"`
	OutcomeTypes         []*OutcomeType `protobuf:"bytes,3,rep,name=outcome_types,json=outcomeTypes,proto3" json:"outcome_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MarketType) Reset()         { *m = MarketType{} }
func (m *MarketType) String() string { return proto.CompactTextString(m) }
func (*MarketType) ProtoMessage()    {}
func (*MarketType) Descriptor() ([]byte, []int) {
	return fileDescriptor_sport_descriptions_3f03905b69aaba44, []int{4}
}
func (m *MarketType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketType.Unmarshal(m, b)
}
func (m *MarketType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketType.Marshal(b, m, deterministic)
}
func (dst *MarketType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketType.Merge(dst, src)
}
func (m *MarketType) XXX_Size() int {
	return xxx_messageInfo_MarketType.Size(m)
}
func (m *MarketType) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketType.DiscardUnknown(m)
}

var xxx_messageInfo_MarketType proto.InternalMessageInfo

func (m *MarketType) GetMarketTypeId() int32 {
	if m != nil {
		return m.MarketTypeId
	}
	return 0
}

func (m *MarketType) GetMarketNameTemplate() string {
	if m != nil {
		return m.MarketNameTemplate
	}
	return ""
}

func (m *MarketType) GetOutcomeTypes() []*OutcomeType {
	if m != nil {
		return m.OutcomeTypes
	}
	return nil
}

type OutcomeType struct {
	OutcomeTypeId int32 `protobuf:"varint,1,opt,name=outcome_type_id,json=outcomeTypeId,proto3" json:"outcome_type_id,omitempty"`
	// event.participants = ["Dinamo", "Shakhtar"]
	// market_params.handicap = 1.5
	// Ex.: "{$participant2} ({-$handicap})" -> "Shakhtar (-1.5)"
	OutcomeNameTemplate  string   `protobuf:"bytes,2,opt,name=outcome_name_template,json=outcomeNameTemplate,proto3" json:"outcome_name_template,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutcomeType) Reset()         { *m = OutcomeType{} }
func (m *OutcomeType) String() string { return proto.CompactTextString(m) }
func (*OutcomeType) ProtoMessage()    {}
func (*OutcomeType) Descriptor() ([]byte, []int) {
	return fileDescriptor_sport_descriptions_3f03905b69aaba44, []int{5}
}
func (m *OutcomeType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutcomeType.Unmarshal(m, b)
}
func (m *OutcomeType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutcomeType.Marshal(b, m, deterministic)
}
func (dst *OutcomeType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutcomeType.Merge(dst, src)
}
func (m *OutcomeType) XXX_Size() int {
	return xxx_messageInfo_OutcomeType.Size(m)
}
func (m *OutcomeType) XXX_DiscardUnknown() {
	xxx_messageInfo_OutcomeType.DiscardUnknown(m)
}

var xxx_messageInfo_OutcomeType proto.InternalMessageInfo

func (m *OutcomeType) GetOutcomeTypeId() int32 {
	if m != nil {
		return m.OutcomeTypeId
	}
	return 0
}

func (m *OutcomeType) GetOutcomeNameTemplate() string {
	if m != nil {
		return m.OutcomeNameTemplate
	}
	return ""
}

func init() {
	proto.RegisterType((*SportDescriptionsRequest)(nil), "xfeed_proto.SportDescriptionsRequest")
	proto.RegisterType((*SportDescriptionsResponse)(nil), "xfeed_proto.SportDescriptionsResponse")
	proto.RegisterType((*SportDescription)(nil), "xfeed_proto.SportDescription")
	proto.RegisterType((*Period)(nil), "xfeed_proto.Period")
	proto.RegisterType((*MarketType)(nil), "xfeed_proto.MarketType")
	proto.RegisterType((*OutcomeType)(nil), "xfeed_proto.OutcomeType")
}

func init() {
	proto.RegisterFile("xfeed_proto/sport_descriptions.proto", fileDescriptor_sport_descriptions_3f03905b69aaba44)
}

var fileDescriptor_sport_descriptions_3f03905b69aaba44 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xdd, 0x4e, 0xf2, 0x40,
	0x10, 0x86, 0xd3, 0x0f, 0x3e, 0x7e, 0xa6, 0xf0, 0xfd, 0x0c, 0x1a, 0x8b, 0x86, 0x40, 0x1a, 0x62,
	0x38, 0xb1, 0x18, 0x3c, 0x33, 0xf1, 0xcc, 0x98, 0x34, 0xf1, 0x2f, 0x95, 0xf3, 0xa6, 0xb0, 0x0b,
	0x69, 0xa4, 0xdd, 0xb5, 0xbb, 0x24, 0x72, 0x3d, 0x5e, 0x84, 0xb7, 0x67, 0xba, 0x5b, 0xec, 0x82,
	0x9c, 0xed, 0xcc, 0xfb, 0xce, 0x3b, 0xcf, 0x2c, 0x0c, 0xdf, 0x17, 0x94, 0x92, 0x90, 0x67, 0x4c,
	0xb2, 0xb1, 0xe0, 0x2c, 0x93, 0x21, 0xa1, 0x62, 0x9e, 0xc5, 0x5c, 0xc6, 0x2c, 0x15, 0x9e, 0x12,
	0xd0, 0x36, 0x5c, 0xa7, 0xfd, 0x25, 0x63, 0xcb, 0x15, 0x1d, 0xab, 0x6a, 0xb6, 0x5e, 0x8c, 0x65,
	0x9c, 0x50, 0x21, 0xa3, 0x84, 0x6b, 0xb7, 0xeb, 0x81, 0xf3, 0x92, 0x27, 0xdd, 0x1a, 0x41, 0x01,
	0x7d, 0x5b, 0x53, 0x21, 0x11, 0xa1, 0xba, 0x8a, 0xd2, 0xa5, 0x63, 0x0d, 0xac, 0x51, 0x33, 0x50,
	0x6f, 0x37, 0x86, 0xee, 0x01, 0xbf, 0xe0, 0x2c, 0x15, 0x14, 0xef, 0x01, 0x7f, 0x62, 0x39, 0xd6,
	0xa0, 0x32, 0xb2, 0x27, 0x3d, 0xcf, 0xe0, 0xf2, 0xf6, 0x33, 0x82, 0xff, 0x62, 0x3f, 0xd5, 0xfd,
	0xb4, 0xe0, 0xdf, 0xbe, 0x0f, 0xbb, 0xd0, 0xd0, 0x2b, 0x62, 0xa2, 0xb8, 0x7e, 0x07, 0x75, 0x55,
	0xfb, 0x04, 0x7b, 0x00, 0x5a, 0x4a, 0xa3, 0x84, 0x3a, 0xbf, 0x14, 0x74, 0x53, 0x75, 0x1e, 0xa3,
	0x84, 0xe2, 0x05, 0xd4, 0x39, 0xcd, 0x62, 0x46, 0x84, 0x53, 0x51, 0x44, 0x9d, 0x1d, 0xa2, 0x67,
	0xa5, 0x05, 0x5b, 0x0f, 0x5e, 0x43, 0x2b, 0x89, 0xb2, 0x57, 0x2a, 0x43, 0xb9, 0xe1, 0x54, 0x38,
	0x55, 0x35, 0x73, 0xb2, 0x33, 0xf3, 0xa0, 0x0c, 0xd3, 0x0d, 0xa7, 0x81, 0x9d, 0x7c, 0xbf, 0x85,
	0x7b, 0x07, 0x35, 0x1d, 0x87, 0x67, 0xd0, 0xd4, 0x81, 0x25, 0x6f, 0x43, 0x37, 0x7c, 0x82, 0x7d,
	0xb0, 0x0b, 0xd1, 0x20, 0x06, 0xdd, 0xca, 0x91, 0xdd, 0x0f, 0x0b, 0xa0, 0xdc, 0x81, 0x43, 0xf8,
	0x63, 0x20, 0x95, 0x89, 0xad, 0x72, 0xb7, 0x4f, 0xf0, 0x12, 0x8e, 0x0a, 0x57, 0x9e, 0x1a, 0x4a,
	0x9a, 0xf0, 0x55, 0x24, 0xb7, 0xf1, 0xa8, 0xb5, 0x3c, 0x7e, 0x5a, 0x28, 0x78, 0x03, 0x6d, 0xb6,
	0x96, 0x73, 0x96, 0xbb, 0xd5, 0xad, 0xfa, 0x7f, 0x9c, 0x9d, 0x5b, 0x9f, 0xb4, 0x43, 0x1d, 0xdb,
	0x62, 0x65, 0x21, 0xdc, 0x18, 0x6c, 0x43, 0xc4, 0x73, 0xf8, 0x6b, 0xa6, 0x95, 0x98, 0x6d, 0x63,
	0xca, 0x27, 0x38, 0x81, 0xe3, 0xad, 0xef, 0x10, 0x68, 0xa7, 0x10, 0x4d, 0xd2, 0x59, 0x4d, 0xb1,
	0x5c, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x62, 0x7e, 0x8a, 0x0a, 0x03, 0x00, 0x00,
}
